name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install minimal test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi requests sqlalchemy pytest httpx

      - name: Run tests
        run: |
          pytest -q
